name: CI Pipeline

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    services:
      redis:
        image: redis:6-alpine
        ports:
          - 6379:6379

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Go
        uses: actions/setup-go@v4
        with:
          go-version: '1.22'

      - name: Verify Go version
        run: go version

      - name: Go mod tidy (clean up dependencies)
        run: go mod tidy

      - name: Install dependencies
        run: go mod download

      - name: Install golangci-lint
        run: |
          curl -sSfL https://raw.githubusercontent.com/golangci/golangci-lint/master/install.sh | sh -s -- -b $(go env GOPATH)/bin v1.52.2

      - name: Run golangci-lint
        run: golangci-lint run

      - name: Run tests
        env:
          REDIS_HOST: 127.0.0.1
          REDIS_PORT: 6379
        run: go test -v ./...

      - name: Build the project
        run: go build -v ./...
